blank_issues_enabled: true
contact_links:
- name: Facebook
  url: https://www.facebook.com/KevinNitro
  about: Facebook cá»§a tui nÃ¨ ğŸ¤
- name: Telegram
  url: https://t.me/KevinNitro
  about: Telegram tháº§m kÃ­n to nhá» ğŸ¤