blank_issues_enabled: true
contact_links:
  - name: Facebook
    url: https://www.facebook.com/KevinNitro
    about: My Facebook ğŸ¤
  - name: Telegram
    url: https://t.me/KevinNitro
    about: My Telegram ğŸ¤
