name: Pre-commit format
on: push
jobs:
  format-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@main
      - uses: pre-commit/action@main
      - name: Update pre-commit hook
        run: pre-commit autoupdate
      - uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: "ğŸ› [pre-commit action]: Auto format"
